# _config.yml
title: "My Documentation Site"
theme: "just-the-docs"
remote_theme: "pmarsceill/just-the-docs"  # Ensure you're using the correct remote theme
docs_dir: "docs"

# Navigation settings for Just the Docs
just_the_docs:
  logo: "/assets/images/logo.png"    # optional, change if you want a logo
  search_enabled: true
  show_nav: true                     # enable the navigation sidebar
  show_toc: true                     # enable the table of contents on each page
  toc_levels: 1..3

# Navigation manually specified
nav:
  - title: "Welcome"
    url: /
    nav_order: 1
  - title: "Setup Guide"
    url: /setup
    nav_order: 2
  - title: "Usage"
    url: /usage
    nav_order: 3
  - title: "Configuration"
    url: /configuration
    nav_order: 4
