# _config.yml
title: "My Documentation Site"
theme: "just-the-docs"  # Make sure this is the correct theme
remote_theme: "pmarsceill/just-the-docs"  # Add this if it's missing
docs_dir: "docs"  # This assumes you are using the /docs folder for your content

# Just the Docs settings
just_the_docs:
  search_enabled: true  # Ensure search is enabled
  show_nav: true  # Ensure sidebar navigation is enabled
  show_toc: true  # Ensure table of contents is enabled on each page
  toc_levels: 1..3  # Table of contents depth
# Navigation manually specified
nav:
  - title: "Welcome"
    url: /
    nav_order: 1
  - title: "Setup Guide"
    url: /setup
    nav_order: 2
  - title: "Usage"
    url: /usage
    nav_order: 3
  - title: "Configuration"
    url: /configuration
    nav_order: 4
